---
- name: Openvpn
  hosts: all
  become: true
  become_method: sudo
  vars:
    # EasyRSA
    easyrsa_generate_dh: true
    easyrsa_servers:
      - name: server
        pass: ~
        cn: ~


    easyrsa_pki_dir: /etc/easyrsa/pki

    # OpenVPN
    openvpn_use_pam: false
    
    openvpn_server: 192.168.100.0 255.255.255.0
    openvpn_server_options:
      - push "route 10.0.0.0 255.255.0.0"

    openvpn_use_ldap: false
    openvpn_keydir: "{{ easyrsa_pki_dir }}"
    openvpn_clients: "{{ easyrsa_clients | map(attribute='name') | list }}"
    openvpn_download_dir: /tmp/

    ## scripting
    openvpn_script_output_directories:
      - /var/log/openvpn-script-out/

    openvpn_script_files:
      - scripts/client-disconnect.sh.j2

    openvpn_inline_scripts:
      - name: my-up-script.sh
        content: |
          #!/usr/bin/env
          echo 'Up!' >> "/var/up.log"
    # Enabled them
    openvpn_download_clients: true
    openvpn_open_firewall: false
    openvpn_route_traffic: false
    openvpn_unified_client_profiles: false
    openvpn_management_enable: false
    openvpn_client_to_client_via_ip: true
  roles:
    - role: easyrsa
    - role: openvpn