---
# easy RSDA vars

# }}}
# Certificates {{{
easyrsa_generate_dh: true

#Openvpn VARS

openvpn_host: "{{ inventory_hostname }}"

openvpn_port: '1194'
openvpn_proto: udp
openvpn_dev: tun
openvpn_bridge: {}
openvpn_max_clients: 100
openvpn_log: /var/log/openvpn.log
openvpn_keepalive: "10 120"
openvpn_ifconfig_pool_persist: ipp.txt
openvpn_comp_lzo: true
openvpn_cipher: BF-CBC
openvpn_status: openvpn-status.log
openvpn_verb: 3
openvpn_user: nobody
openvpn_group: nogroup
openvpn_resolv_retry: infinite

openvpn_management_enable: true
openvpn_management_host: localhost
openvpn_management_port: 7505
openvpn_management_pass: ~

openvpn_route_traffic: false

# Whether to create an iptables rule to allow connections to the openvpn server.
openvpn_open_firewall: true
openvpn_out_interface: ~
openvpn_nat_ranges: []
openvpn_nat_address: []

openvpn_route_ranges: []
openvpn_dns_servers: []
# Make clients certificate

openvpn_clients_revoke: []
# Revoke clients certificates

openvpn_client_options: []
openvpn_unified_client_profiles: false
openvpn_download_clients: true
openvpn_download_dir: "/tmp/"
openvpn_download_extract: "{{ openvpn_download_clients }}"
openvpn_client_to_client: false

openvpn_client_to_client_via_ip: false

openvpn_ccd: /etc/openvpn/ccd/

openvpn_ccd_configs: []
openvpn_client_conf_template: client.conf.j2
openvpn_ldap_tlsenable: 'false'
openvpn_ldap_follow_referrals: 'false'
openvpn_simple_auth: false
openvpn_simple_auth_password: ""
openvpn_tls_auth: false
openvpn_tls_key: "ta.key"
openvpn_script_output_directories: []
openvpn_scripts_dir: "{{ openvpn_etcdir }}/scripts/"
openvpn_script_files: []
openvpn_inline_scripts: []

# NOTE The role also comes with `up` and `down` scripts that are used if you
# enable bridge configuration (see `openvpn_bridge`). These are handled by the
# bridge-specific tasks.
# }}}